DSCC.MVC.11456/Models/Blog.cs
using System;
namespace DSCC.MVC._11456.Models
{
    public class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string CoverImage { get; set; }
        public string Author { get; set; }
        public string Content { get; set; }
        public string CreatedAt { get; set; }
        public int LikeCount { get; set; }
        public University University { get; set; }
    }
}

DSCC.MVC.11456/Models/ErrorViewModel.cs
namespace DSCC.MVC._11456.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

DSCC.MVC.11456/Models/University.cs
using System;
namespace DSCC.MVC._11456.Models
{
    public class University
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string Courses { get; set; }
        public decimal Rating { get; set; }
        public string Admission { get; set; }
        public int Scolarship { get; set; }
        public int TuitionFee { get; set; }
        public int EstablishedIn { get; set; }
        public string Image { get; set; }
        public string Location { get; set; }
    }
}

DSCC.MVC.11456/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Intrinsics.X86;
using System.Threading.Tasks;
using DSCC.MVC._11456.Models;
using DSCC.MVC._11456.Services;
using Microsoft.AspNetCore.Mvc;

namespace DSCC.MVC._11456.Controllers
{
    public class BlogController : Controller
    {
        private readonly IApiService _apiService;

        public BlogController(IApiService apiService)
        {
            _apiService = apiService;
        }

        public async Task<IActionResult> Index()
        {
            var blogs = await _apiService.GetAllBlogs();
            return View(blogs);
        }

        public async Task<IActionResult> Details(int id)
        {
            var blog = await _apiService.GetBlogById(id);
            return View(blog);
        }

        // Action method to display the edit form for blog
        public async Task<IActionResult> Edit(int id)
        {
            var blog = await _apiService.GetBlogById(id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // Action method to handle the submission of the edit form for blog
        [HttpPost]
        public async Task<IActionResult> Edit(Blog blog)
        {
            if (!ModelState.IsValid)
            {
                return View(blog);
            }

            // Calling API to update the blog
            await _apiService.UpdateBlog(blog.Id, blog);

            // Redirecting
            return RedirectToAction(nameof(Index));
        }

        // Action method to handle deletion of blog
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var blog = await _apiService.GetBlogById(id);
            if (blog == null)
            {
                return NotFound();
            }

            // Calling API to delete the blog
            await _apiService.DeleteBlog(id);

            // Redirecting
            return RedirectToAction(nameof(Index));
        }
    }
}

DSCC.MVC.11456/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DSCC.MVC._11456.Models;

namespace DSCC.MVC._11456.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DSCC.MVC.11456/Controllers/UniversityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DSCC.MVC._11456.Models;
using DSCC.MVC._11456.Services;
using Microsoft.AspNetCore.Mvc;

namespace DSCC.MVC._11456.Controllers
{
    public class UniversityController : Controller
    {
        private readonly IApiService _apiService;

        public UniversityController(IApiService apiService)
        {
            _apiService = apiService;
        }

        public async Task<IActionResult> Index()
        {
            var universities = await _apiService.GetAllUniversities();
            return View(universities);
        }

        public async Task<IActionResult> Details(int id)
        {
            var university = await _apiService.GetUniversityById(id);
            return View(university);
        }

        // Action method to display the edit form for uni
        public async Task<IActionResult> Edit(int id)
        {
            var university = await _apiService.GetUniversityById(id);
            if (university == null)
            {
                return NotFound();
            }

            return View(university);
        }

        // Action method to handle the submission of the edit form for uni
        [HttpPut]
        public async Task<IActionResult> Edit(University university)
        {
            if (!ModelState.IsValid)
            {
                return View(university);
            }

            // Calling API to update the uni
            await _apiService.UpdateUniversity(university.Id, university);

            // Redirecting
            return RedirectToAction(nameof(Index));
        }

        // Action method to handle deletion of uni
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var university = await _apiService.GetUniversityById(id);
            if (university == null)
            {
                return NotFound();
            }

            // Calling API to delete the university
            await _apiService.DeleteUniversity(id);

            // Redirecting
            return RedirectToAction(nameof(Index));
        }

        // Create Uni Page View
        public ActionResult Create()
        {
            return View();
        }

        // Action method to create new uni
        [HttpPost]
        public async Task<IActionResult> Create(University university)
        {
            await _apiService.CreateUniversity(university);

            // Redirecting
            return RedirectToAction(nameof(Index));
        }
    }
}

DSCC.MVC.11456/Views/Blog/Details.cshtml
@model DSCC.MVC._11456.Models.Blog

@{
    ViewData["Title"] = "Details of " + Model.Title;
}

<h1>@Model.Title (by @Model.Author)</h1>
<p>@Model.Content</p>
<p>Likes: @Model.LikeCount</p>

@Html.ActionLink("Back to list", "Index")

DSCC.MVC.11456/Views/Blog/Edit.cshtml
@model DSCC.MVC._11456.Models.Blog

@{
    ViewData["Title"] = "Editing " + Model.Title;
}

<h1 class="text-center mb-4">Edit Blog</h1>

<div class="container">
    <form asp-action="Edit" asp-controller="Blog" method="post">
        <input type="hidden" asp-for="Id" />

        <div class="form-group mb-3">
            <label asp-for="Title" class="form-label"></label>
            <input asp-for="Title" class="form-control" required>
        </div>

        <div class="form-group mb-3">
            <label asp-for="CoverImage" class="form-label"></label>
            <textarea asp-for="CoverImage" class="form-control" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Author" class="form-label"></label>
            <textarea asp-for="Author" class="form-control" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Content" class="form-label"></label>
            <textarea asp-for="Content" class="form-control" rows="4" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="CreatedAt" class="form-label"></label>
            <textarea asp-for="CreatedAt" class="form-control" rows="4" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="LikeCount" class="form-label"></label>
            <textarea asp-for="LikeCount" class="form-control" rows="4" type="number" required></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Update Blog</button>
    </form>
</div>

DSCC.MVC.11456/Views/Blog/Index.cshtml
@model IEnumerable<DSCC.MVC._11456.Models.Blog>

@{
    ViewData ["Title"] = "Universities Blog";
}

<h1 class="text-center mb-4">Blogs</h1>

@if (!Model.Any())
{
    <div class="alert alert-info" role="alert"> No Blogs </div>
}

else
{
    <div class="container">
        <div class="row">
            @foreach (var blog in Model)

            {
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-header"> Popular Blogs </div>
                        <div class="card-body">
                            <h5 class="card-title">@blog.Title</h5>
                            <p class="card-text">@blog.Content</p>
                            <a href="@Url.Action("Details", "Blog", new { id = blog.Id })" class="btn btn-primary">View Details</a>
                            <form asp-action="Delete" asp-controller="Blog" asp-route-id="@blog.Id" method="post" class="d-inline">
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this blog?');">
                                    Delete
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
}

DSCC.MVC.11456/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This website was made for DSCC by 00011456</p>
</div>

DSCC.MVC.11456/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DSCC.MVC._11456</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DSCC.MVC._11456.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DSCC.MVC._11456</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="University" asp-action="Index">Universities</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DSCC.MVC._11456 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DSCC.MVC.11456/Views/University/Create.cshtml
@model DSCC.MVC._11456.Models.University

@{
    ViewData["Title"] = "New University";
}

<h1 class="text-center mb-4">Create University</h1>

<div class="container">
    <form asp-action="Create" asp-controller="University" method="post">
        <div class="form-group mb-3">
            <label asp-for="Name" class="form-label"></label>
            <input asp-for="Name" class="form-control" required>
        </div>

        <div class="form-group mb-3">
            <label asp-for="ShortName" class="form-label"></label>
            <textarea asp-for="ShortName" class="form-control" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Description" class="form-label"></label>
            <textarea asp-for="Description" class="form-control" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Courses" class="form-label"></label>
            <textarea asp-for="Courses" class="form-control" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Rating" class="form-label"></label>
            <textarea asp-for="Rating" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Admission" class="form-label"></label>
            <textarea asp-for="Admission" class="form-control" rows="4" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Scolarship" class="form-label"></label>
            <textarea asp-for="Scolarship" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="TuitionFee" class="form-label"></label>
            <textarea asp-for="TuitionFee" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="EstablishedIn" class="form-label"></label>
            <textarea asp-for="EstablishedIn" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Image" class="form-label"></label>
            <textarea asp-for="Image" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Location" class="form-label"></label>
            <textarea asp-for="Location" class="form-control" type="number" required></textarea>
        </div>



        <button type="submit" class="btn btn-primary">Create University</button>
    </form>
</div>

DSCC.MVC.11456/Views/University/Details.cshtml
@model DSCC.MVC._11456.Models.University

@{
    ViewData["Title"] = "Details of " + Model.Name;
}

<h1>@Model.Name (@Model.ShortName)</h1>
<p>@Model.Location</p>
<p>@Model.Description</p>

@Html.ActionLink("Back to list", "Index")

DSCC.MVC.11456/Views/University/Edit.cshtml
@model DSCC.MVC._11456.Models.University

@{
    ViewData["Title"] = "Editing " + Model.Name;
}

<h1 class="text-center mb-4">Edit University</h1>

<div class="container">
    <form asp-action="Edit" asp-controller="University" method="post">
        <input type="hidden" asp-for="Id" />

        <div class="form-group mb-3">
            <label asp-for="Name" class="form-label"></label>
            <input asp-for="Name" class="form-control" required>
        </div>

        <div class="form-group mb-3">
            <label asp-for="ShortName" class="form-label"></label>
            <textarea asp-for="ShortName" class="form-control" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Description" class="form-label"></label>
            <textarea asp-for="Description" class="form-control" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Courses" class="form-label"></label>
            <textarea asp-for="Courses" class="form-control" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Rating" class="form-label"></label>
            <textarea asp-for="Rating" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Admission" class="form-label"></label>
            <textarea asp-for="Admission" class="form-control" rows="4" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Scolarship" class="form-label"></label>
            <textarea asp-for="Scolarship" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="TuitionFee" class="form-label"></label>
            <textarea asp-for="TuitionFee" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="EstablishedIn" class="form-label"></label>
            <textarea asp-for="EstablishedIn" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Image" class="form-label"></label>
            <textarea asp-for="Image" class="form-control" type="number" required></textarea>
        </div>

        <div class="form-group mb-3">
            <label asp-for="Location" class="form-label"></label>
            <textarea asp-for="Location" class="form-control" type="number" required></textarea>
        </div>



        <button type="submit" class="btn btn-primary">Update University</button>
    </form>
</div>

DSCC.MVC.11456/Views/University/Index.cshtml
@model IEnumerable<DSCC.MVC._11456.Models.University>

@{
    ViewData ["Title"] = "Uzbekistan's Universities";
}

<h1 class="text-center mb-4">Universities
    <a href="@Url.Action("Create", "University")" class="btn btn-primary">Create</a>
    </h1>

@if (!Model.Any())
{
    <div class="alert alert-info" role="alert"> No Universities </div>
}

else
{
    <div class="container">
        <div class="row">
            @foreach (var uni in Model)

            {
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-header"> Top University
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">@uni.Name</h5>
                            <p class="card-text">@uni.Description</p>
                            <a href="@Url.Action("Details", "University", new { id = uni.Id })" class="btn btn-primary">View Details</a>
                            <a href="@Url.Action("Edit", "University", new { id = uni.Id })" class="btn btn-secondary">Edit</a>
                            <form asp-action="Delete" asp-controller="University" asp-route-id="@uni.Id" method="post" class="d-inline">
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this university?');">
                                    Delete
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
}